<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="linuxgateway-data\**" />
    <None Remove="linuxgateway-data\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutomationUnityBuildIOS.Tests" />
  </ItemGroup>
</Project>
