<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(ExcludeCli)' == 'true'">Library</OutputType>
    <OutputType Condition="'$(ExcludeCli)' != 'true'">Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BuildServer\**\*.cs" />
    <Compile Remove="LinuxGateway\**\*.cs" />
    <Compile Remove="AutomationUnityBuildIOS.Tests\**\*.cs" />
    <Compile Remove="DesktopApp\**\*.cs" />
    <Compile Remove="Cli\Cli.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Compile Remove="Cli\CommandLineParser.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Compile Remove="Cli\ShortcutCommands.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Compile Remove="ConsoleUi\HelpPrinter.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Compile Remove="ConsoleUi\InteractiveMenu.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Compile Remove="Program.cs" Condition="'$(ExcludeCli)' == 'true'" />
    <Content Remove="BuildServer\**\*" />
    <Content Remove="LinuxGateway\**\*" />
    <Content Remove="AutomationUnityBuildIOS.Tests\**\*" />
    <Content Remove="DesktopApp\**\*" />
    <None Remove="BuildServer\**\*" />
    <None Remove="LinuxGateway\**\*" />
    <None Remove="AutomationUnityBuildIOS.Tests\**\*" />
    <None Remove="DesktopApp\**\*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutomationUnityBuildIOS.Tests" />
    <InternalsVisibleTo Include="DesktopApp" />
  </ItemGroup>

</Project>
